### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by prsolucoes** [Alan881/AACarousel#1]
Hi,

Very nice.

It have Carthage support?

Can you add it not?

Thanks.

**Comment by Alan881** [comment]
Thanks for your opinion.
I will upload my project to Carthage recently.

**Comment by prsolucoes** [comment]
Thanks, im waiting to add to my project.

**Comment by Alan881** [comment]
Hi, 
I already update my project to support Carthage.
Please try to install it.
Thanks.

**Comment by prsolucoes** [comment]
Im trying.

1 - It create the framework
2 - I have imported framework
3 - I import module AACarousel
4 - AACarousel is not recognized when build

See:

<img width="984" alt="screenshot 2017-07-20 00 27 10" src="https://user-images.githubusercontent.com/395096/28399226-3c9148b6-6ce2-11e7-8b01-615482687b05.png">

**Comment by Alan881** [comment]
Sorry, I fixed the issue.
Please update Carthage.
Thanks.

**Comment by prsolucoes** [comment]
Working. Thanks.

**Comment by IOSDeveloperProgrammer** [comment]
Hi Recently I was installing pod it. and am getting same error above it (undecleared AACarousel). i don't know how to install carthage and use it. please help me
