### ISSUE TITLE
Banners loaded but not showed

### ISSUE THREAD

**Issue by prsolucoes** [Alan881/AACarousel#3]
Hi,

I put a log on "downloadImages" and see that all 3 banner is loaded, but it still on first banner with blank background without image. The image only show when i change page and back.

How can i solve it? Banner need be showed on the current page when it is loaded without need change page.

Thanks.

**Comment by Alan881** [comment]
Can you show your sample code ?
Thanks.

**Comment by prsolucoes** [comment]
Wow... It is working now man. Thanks :)
