### ISSUE TITLE
Bug when no banner is on carousel

### ISSUE THREAD

**Issue by prsolucoes** [Alan881/AACarousel#5]
Bug when no banner is on carousel

If you don't put any banner on carousel, but show it, when tap the project crash.

Line that crash:

```swift
//MARK:- UITapGestureRecognizer
    @objc fileprivate func didSelectImageView() {
        
        if let delegate = delegate {
            if let method = delegate.didSelectCarouselView {
                method(self, currentIndex)    // <--- crash
                return
            }
        }
}
```

I think that it is simple, can you fix it?
Thanks.

**Comment by Alan881** [comment]
I have fixed it.
You can update and try it.
Thank you for your note.

**Comment by prsolucoes** [comment]
It works man, fixed. Thanks.
